# File: hauki-admin-ui/azure-pipelines.yml

# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - release-*
  paths:
    exclude:
    - README.md

# By default, use self-hosted agents
pool: Default

# Opting out of pull request validation
pr: none

resources:
  repositories:
  # Azure DevOps repository
  - repository: trigger-test-pipelines
    type: git
    # project/repository
    name: trigger-test/trigger-test-pipelines

extends:
  template: azure-pipelines-hauki-admin-ui-release.yml@trigger-test-pipelines
